# Generated by Django 4.2.1 on 2024-10-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='recommendation',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
