# Generated by Django 4.2.1 on 2024-10-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question_type',
            name='type_en',
        ),
        migrations.AlterField(
            model_name='question_type',
            name='type',
            field=models.CharField(blank=True, default=None, max_length=36, null=True),
        ),
    ]
