# Generated by Django 4.2.1 on 2024-11-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_remove_question_type_type_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='weight',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
