"""
Django settings for root project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import environ


env = environ.Env()
environ.Env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

DEBUG = True
# DEBUG = False
ALLOWED_HOSTS = ["localhost", "127.0.0.1"]


# # HTTPS settings
SESSION_COOKIE_SECURE = True
SESSION_COOKIE_HTTPONLY = True
CSRF_TOKEN_SECURE = True
CSRF_COOKIE_SECURE = True
CSRF_COOKIE_HTTPONLY = True

# SECURE_SSL_REDIRECT = True

# # HSTS Settings
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_PRELOAD = True
SECURE_HSTS_INCLUDE_SUBDOMAINS = True



INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "channels",
    "django_bootstrap5",
    "base.apps.BaseConfig",
    "accounts.apps.AccountsConfig",
    "audit.apps.AuditConfig",
    "reporter.apps.ReporterConfig",
    "Analytics.apps.AnalyticsConfig",
    "django_extensions",
    "axes",
    "rest_framework",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "root.middlewares.EnsureUserInformationMiddleware",
    "root.middlewares.AdminSiteRestrictionMiddleware",
    "root.middlewares.PermissionsPolicyMiddleware",
    "root.middlewares.SimpleMiddleware",
    "axes.middleware.AxesMiddleware",
]

ROOT_URLCONF = "root.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "base.templatetags.context_processors.view_name",
            ],
        },
    },
]

WSGI_APPLICATION = "root.wsgi.application"
ASGI_APPLICATION = "root.asgi.application"


# Database Configuration Based on Environment Variables
DATABASES = {}
DB_ENGINE = env("DB_ENGINE", default="sqlite3").strip()
if DB_ENGINE == "sqlite3":
    db_name = env("DB_NAME", default="db.sqlite3")
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / f"{db_name}.sqlite3",
    }
elif DB_ENGINE=="mysql":
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST'),
        'PORT': env('DB_PORT', default='3306'),
    }
else:
    raise ValueError(f"Unsupported DB_ENGINE value: {DB_ENGINE}")


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators


AUTHENTICATION_BACKENDS = [
    # AxesStandaloneBackend should be the first backend in the AUTHENTICATION_BACKENDS list.
    "axes.backends.AxesStandaloneBackend",
    # Django ModelBackend is the default authentication backend.
    "django.contrib.auth.backends.ModelBackend",
]

AXES_FAILURE_LIMIT = 10

AXES_LOCK_OUT_AT_FAILURE = True

AXES_COOLOFF_TIME = 120


AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "root.validators.MinimumLengthValidator",
    },
    {
        "NAME": "root.validators.UppercaseValidator",
    },
    {
        "NAME": "root.validators.LowercaseValidator",
    },
    {
        "NAME": "root.validators.SpecialCharValidator",
    },
    {
        "NAME": "root.validators.NumericalPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en'
LANGUAGES = [
    ('en', 'English'),
]
TIME_ZONE = "Europe/Riga"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

STATICFILES_DIRS = [
    BASE_DIR / "accounts" / "static",  
    BASE_DIR / "Analytics" / "static",  
    BASE_DIR / "audit" / "static",  
    BASE_DIR / "base" / "static",  
    BASE_DIR / "static", 
]



MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGIN_REDIRECT_URL = "Dashboard"
LOGIN_URL = "/members/login_user"

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST =  env('EMAIL_HOST'),
EMAIL_PORT =  env('EMAIL_PORT'),
EMAIL_HOST_USER =  env('EMAIL_HOST_USER'),
EMAIL_HOST_PASSWORD =  env('EMAIL_HOST_PASSWORD'),
EMAIL_USE_TLS =  env('EMAIL_USE_TLS'),
# EMAIL_USE_SSL =  env('EMAIL_USE_SSL'),

PORTION_SIZE = 350
LOGGER_DATA_KEEPING_DAYS = 3

CSP_REPORT_ONLY = True

X_FRAME_OPTIONS = 'DENY'



